# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false
